export const UtmWhitelist = [
  'from',
  'openstat',
  'openstat_service',
  'openstat_campaign',
  'openstat_ad',
  'openstat_source',
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_content',
  'utm_term',
  'utm_referrer',
  'gсlid',
  'fbclid',
  'yclid',
  'referrer',
];
